### ISSUE TITLE
Generic Ops Question

### ISSUE THREAD

**Issue by connortsui20** [thomasbarrett/io-uring-async#1]
I stumbled upon this recently since I was looking at `tokio-uring` and was hoping for something lower level, and this seems to be what I was looking for!

I was wondering if there was a reason behind making all `Op`s generic over a `cqueue::Entry` trait, which seems to be sort of a re-export of `io_uring::cqueue`'s and `io_uring::squeue`'s methods. I am not super familiar with using `io_uring`, so maybe this is a stupid question, but what are some examples of when you would want to implement a `cqueue::Entry` trait on your own type (rather than using the types `io_uring` provides)? It seems like it would make implementation easier to just use the types the `io-uring` crate provides.

Really nice job on this! I'm interested to see where this goes, if you decide to take it further.

**Comment by thomasbarrett** [comment]
Glad you like it @Connortsui20. I am considering throwing it on crates.io. 

The choice to add a cqueue::Entry and squeue::Entry trait was made in order to support the extended `squeue::Entry128` and `cqueue::Entry32` types defined in the `io_uring` crate in addition to the standard `squeue::Entry` and `cqueue::Entry`. The `io_uring` library uses an empty `EntryMarker` trait, but the trait does not have all methods necessary to hook into the tokio runtime (e.g. the `user_data` method). 

See [this](https://lore.kernel.org/all/20220308152105.309618-2-joshi.k@samsung.com/) link for more information about extended io_uring entry types. I have been working on and off on building a io_uring nvme passthrough command library and a rust ublk library  that make use of this crate (both of which use extended entry types).

**Comment by connortsui20** [comment]
Thank you for the response! Would love to see this on crates.io.

Personally, I'm working on something very similar to your crate (i.e. I copied an pasted a lot of your code) that is going to attempt to make the `Op`s thread safe by using a concurrent hash map to store the lifecycles instead of the slab allocator. Thanks again for your work!
